### ISSUE TITLE
judging cycle flow

### ISSUE THREAD

**Issue by patriciali** [patriciali/wingman#15]
- select competitor
- select round (limit to ongoing? limit to competitor?)
- query for times so far (sanity check)
- inspection + solving flow
- submit: JSON object with registrationId, solveTime, solveIndex

here is some stuff for my personal reference because I have no memory:
SolveTime object http://www.jflei.com/jChester/
penalties https://github.com/cubing/ccm/blob/master/both/__wca.js#L277
API https://live.cubing.net/api OR http://staging.live.jflei.com/api

@jfly fyi

**Comment by jfly** [comment]
We can definitely offload work to the server =). What does select competitor onwards mean?

**Comment by patriciali** [comment]
it was bad formatting. I haven't really looked at this too much yet, but the API you have so far looks fine. I'll let you know if something different would work better.
